name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.cs'

jobs:
  lint-and-static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Use your actual version

      - name: Restore dependencies
        run: dotnet restore

      - name: Run code formatter (dotnet format)
        run: dotnet format --verify-no-changes --severity error

      - name: Run static analysis with warnings as errors
        run: dotnet build --no-restore -warnaserror
