name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.cs'

jobs:
  lint-and-static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install CSharpier
        run: dotnet tool install -g csharpier

      - name: Run CSharpier to check formatting
        run: csharpier check Main/Build.cs

      - name: Install Roslynator CLI
        run: dotnet tool install -g roslynator.cli

      - name: Run static analysis with Roslynator
        run: |
          roslynator analyze . \
            --file-extension .cs \
            --report-format text \
            --severity-level warning || true