name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '**/*.cs'

jobs:
  lint-and-static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust to your project's version

      - name: Install CSharpier as a .NET global tool
        run: dotnet tool install --global csharpier

      - name: Add .NET global tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run CSharpier to check formatting
        run: dotnet csharpier check .

      - name: Run static analysis (dotnet build)
        run: dotnet build -warnaserror
